stages:
    - test
    - doc
    - code_quality
    - deploy

variables:
    EXCLUDE_PYTHON: 36
    CB_URL: http://134.130.166.184:1026
    IOTA_URL: http://134.130.166.184:4041
    QL_URL: http://134.130.166.184:8668
    MQTT_BROKER_URL: mqtt://134.130.166.184:1883
    

include:
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'python/code-quality/pylint.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'python/doc/sphinxdoc.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'pages/pages.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'python/unit-tests/unittest.gitlab-ci.yml'
    - project: 'EBC/EBC_all/gitlab_ci/templates'
      file: 'python/unit-tests/coverage.gitlab-ci.yml'
