name: Test-Execution
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
      CB_URL: http://localhost:1026
      IOTA_URL: http://localhost:4041
      QL_URL: http://localhost:8668

    steps:
    - name: Checkout code
      uses: actions/checkout@v2   
    - name: Run FIWARE setup in docker
      run: docker-compose run
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: python .tests/clients/test_ngsi_v2_cb.py
    - name: Stop Docker Containers
      run: docker stop $(docker ps -a -q) 
    - name: Remove Docker Containers
      run: docker rm $(docker ps -a -q)
